POST http://localhost:3000/users/
Content-Type: application/json 

{
    "username":"raj123",
    "email":"raj@example.com",
    "password":"password1",
    "location":"Delhi"
} 

###

POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "raj123",
  "password": "password1"
}

